### ISSUE TITLE
problem calling cnv with ERDS.

### ISSUE THREAD

**Issue by pyghost504** [igm-team/ERDS#2]
Hi,
       Please i am new to some of these softwares, i tried calling CNV with some set of data i have following the ERDS pipeline but it keeps on with these errors, please could you let me know what the problem is?
these are my inputs :
perl erds_pipeline.pl -b /mnt/e/SNV_GATK_NVG/pass_snv/Quartet_DNA_ILM_NVG_LCL5_1_20170329_sorted_RG_RmDup.bam -v /mnt/e/SNV_GATK_NVG/Quartet_DNA_ILM_NVG_LCL5_1_20170329_XJT_BWA_HC_SNV_RAW.vcf -o /mnt/e/SNV_GATK_NVG/benue/ -r /mnt/e/ERDS/erds_tcag/src/GRCh38_full_analysis_set_plus_decoy_hla.fa

and i get errors like this:

Error code for chrHLA-DRB1*16:02:01 is 0
[Tue Dec 11 17:49:18 2018] PID 9215 is performing computation for chrchrUn_JTFH01001990v1_decoy
Error code for chrchrUn_JTFH01001993v1_decoy is 0
Error: File /mnt/e/SNV_GATK_NVG/benue//cnv/gcbin/0.gcbin not found
Use of uninitialized value $in in substitution (s///) at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 62.
Use of uninitialized value $in in split at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 63.
Use of uninitialized value in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 64.
Use of uninitialized value in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 64.
Error: File /mnt/e/SNV_GATK_NVG/benue//cnv/gcbin/1.gcbin not found
Use of uninitialized value $in in substitution (s///) at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 62.
Use of uninitialized value $in in split at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 63.
Use of uninitialized value in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 64.
Use of uninitialized value in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 64.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
Redundant argument in printf at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 166.
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr1.rd
Can't open /mnt/e/SNV_GATK_NVG/benue//cnv/chr1.vit at /mnt/e/SNV_GATK_NVG/benue//script/em.pl line 95.
17:51:48 Dec 11 2018 ERDS finished step 2 in RPG...
17:51:48 Dec 11 2018 ERDS stared step 3 in RPG...
[Tue Dec 11 17:51:48 2018] PID 17085 is performing computation for chrchrY
[Tue Dec 11 17:51:48 2018] PID 17086 is performing computation for chrchrX
[Tue Dec 11 17:51:48 2018] PID 17088 is performing computation for chrchr22
[Tue Dec 11 17:51:48 2018] PID 17090 is performing computation for chrchr21
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chrX.rd
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr22.rd
[Tue Dec 11 17:51:48 2018] PID 17086 is performing computation for chrchr19
[Tue Dec 11 17:51:48 2018] PID 17085 is performing computation for chrchr20
[Tue Dec 11 17:51:48 2018] PID 17088 is performing computation for chrchr18
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr21.rd
[Tue Dec 11 17:51:48 2018] PID 17090 is performing computation for chrchr17
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr19.rd
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr20.rd
no chromosome /mnt/e/SNV_GATK_NVG/benue//cnv/chr17.rd

i couldn't paste all the errors, so i picked where they all differs. please can you help how i could fix this? thank you

**Comment by warjaSBG** [comment]
Hi, I have a similar problem. For some reason, it seems like ERDS have an issue tracking down output_dir that is located in the current working dir.
I checked, and all files that the tool reported missing are present in the output_dir.


2019-04-17T14:18:26.416702282Z Can't open output_dir/rc/1.rc at output_dir/script/pre_hmm.pl line 55.
2019-04-17T14:18:26.444475071Z Error: File output_dir/cnv/gcbin/0.gcbin not found 
2019-04-17T14:18:26.444739859Z Use of uninitialized value $in in substitution (s///) at output_dir/script/em.pl line 62.
2019-04-17T14:18:26.444749043Z Use of uninitialized value $in in split at output_dir/script/em.pl line 63.
2019-04-17T14:18:26.444752579Z Use of uninitialized value in printf at output_dir/script/em.pl line 64.
2019-04-17T14:18:26.444755974Z Use of uninitialized value in printf at output_dir/script/em.pl line 64.
2019-04-17T14:18:26.445777458Z Error: File output_dir/cnv/gcbin/1.gcbin not found 
2019-04-17T14:18:26.445931895Z Use of uninitialized value $in in substitution (s///) at output_dir/script/em.pl line 62.
2019-04-17T14:18:26.445943313Z Use of uninitialized value $in in split at output_dir/script/em.pl line 63.
2019-04-17T14:18:26.445948979Z Use of uninitialized value in printf at output_dir/script/em.pl line 64.
2019-04-17T14:18:26.445954159Z Use of uninitialized value in printf at output_dir/script/em.pl line 64.
2019-04-17T14:18:26.446928505Z Error: File output_dir/cnv/gcbin/2.gcbin not found

**Comment by snashraf** [comment]
Hi @pyghost504 and @warjaSBG 

Were you able to solve this issue?

Regards,
Najeeb

**Comment by trjojack** [comment]
What was the solution to this issue? I'm currently getting this error:

9:31:50 May 14 2024	ERDS finished step 0 in 0043429181_S10_L002...
9:31:50 May 14 2024	ERDS stared step 1 in 0043429181_S10_L002...
Can't open ./ERDS/0043429181_S10_L002.erds.cnv.out/rc/1.rc at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/pre_hmm.pl line 55.
9:31:51 May 14 2024	ERDS finished step 1 in 0043429181_S10_L002...
9:31:51 May 14 2024	ERDS stared step 2 in 0043429181_S10_L002...
Error: File ./ERDS/0043429181_S10_L002.erds.cnv.out/cnv/gcbin/0.gcbin not found 
Use of uninitialized value $in in substitution (s///) at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 62.
Use of uninitialized value $in in split at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 63.
Use of uninitialized value in printf at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 64.
Use of uninitialized value in printf at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 64.
Error: File ./ERDS/0043429181_S10_L002.erds.cnv.out/cnv/gcbin/1.gcbin not found 
Use of uninitialized value $in in substitution (s///) at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 62.
Use of uninitialized value $in in split at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 63.
Use of uninitialized value in printf at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 64.
Use of uninitialized value in printf at ./ERDS/0043429181_S10_L002.erds.cnv.out/script/em.pl line 64.
Error: File ./ERDS/0043429181_S10_L002.erds.cnv.out/cnv/gcbin/2.gcbin not found

**Comment by trjojack** [comment]
I solved this by running make in the src folder, not just the hmm and phmm folders, in order to build the read_bam.cpp file in src folder.
